env:
  browser: true
  es2021: true

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module
  project: tsconfig.json

plugins:
  - react
  - '@typescript-eslint'

rules:
  default-case: error
  no-async-promise-executor: error
  no-await-in-loop: error
  no-console: warn
  no-misleading-character-class: error
  no-multi-assign: error
  no-multi-str: error
  no-nested-ternary: error
  no-new: error
  no-new-object: error
  no-new-symbol: error
  no-new-wrappers: error
  no-obj-calls: error
  no-path-concat: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow-restricted-names: error
  no-sparse-arrays: error
  no-tabs: error
  no-this-before-super: error
  prefer-numeric-literals: error
  prefer-object-spread: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  sort-imports: 'off'
  symbol-description: error

  '@typescript-eslint/member-ordering': error
  '@typescript-eslint/method-signature-style': error
  '@typescript-eslint/no-base-to-string': error
  '@typescript-eslint/no-confusing-non-null-assertion': error
  '@typescript-eslint/no-dynamic-delete': error
  '@typescript-eslint/no-floating-promises': error
  '@typescript-eslint/no-implicit-any-catch': error
  '@typescript-eslint/no-require-imports': error
  '@typescript-eslint/no-unnecessary-boolean-literal-compare': error
  '@typescript-eslint/no-unnecessary-qualifier': error
  '@typescript-eslint/no-unnecessary-type-arguments': error
  '@typescript-eslint/no-unnecessary-type-constraint': error
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/prefer-includes': error
  '@typescript-eslint/prefer-nullish-coalescing': error
  '@typescript-eslint/prefer-optional-chain': error
  '@typescript-eslint/prefer-readonly': error
  '@typescript-eslint/prefer-string-starts-ends-with': error
  '@typescript-eslint/prefer-ts-expect-error': 0
  '@typescript-eslint/promise-function-async': error
  '@typescript-eslint/require-array-sort-compare': error
  '@typescript-eslint/sort-type-union-intersection-members': error
  '@typescript-eslint/switch-exhaustiveness-check': error
  '@typescript-eslint/type-annotation-spacing': error
  '@typescript-eslint/unified-signatures': error
  'react/react-in-jsx-scope': 0
  "@typescript-eslint/no-floating-promises": 0
